allowBuilds:
  esbuild: false
minimumReleaseAgeExclude:
  - '@kubohiroya/turbowarp-extension-template@0.4.0'
  - '@kubohiroya/vite-plugin-turbowarp-extension@0.4.0'
  - '@kubohiroya/turbowarp-camera-source@0.4.0 || 0.5.0 || 0.7.0'
  - '@kubohiroya/turbowarp-aframe@0.4.0 || 0.5.0'
  - '@kubohiroya/turbowarp-webrtc@0.3.0'
  - '@kubohiroya/turbowarp-time-space-sync@0.1.0'
